=== RAFSoftLab/marcfxeditor/marcfx/src/rs/edu/raf/marcfx/marc21format/xmlfiles/marc21_formatNovo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by Srđan Škrbić (PMF, Department of Mathematics and Informatics) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="format">
		<xs:annotation>
			<xs:documentation>UNIMARC and MARC21 format</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="leader"/>
				<xs:element ref="directory" minOccurs="0"/>
				<xs:element ref="controlfield" maxOccurs="unbounded"/>
				<xs:element ref="datafield" maxOccurs="unbounded"/>
				<xs:element ref="externalCodeList" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="leader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="charposition" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional" default="LEADER"/>
			<xs:attribute name="repeatable" type="xs:boolean" use="required" fixed="false"/>
			<xs:attribute name="mandatory" type="xs:boolean" use="optional" fixed="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="directory">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="charposition" maxOccurs="3"/>
			</xs:sequence>
			<xs:attribute name="repeatable" type="xs:boolean" use="required" fixed="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="controlfield">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="charposition" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="repeatable" type="xs:boolean" use="required"/>
			<xs:attribute name="mandatory" type="xs:boolean" use="optional"/>
			<xs:attribute name="materialType" type="materialTypeType" use="optional"/>
			<xs:attribute name="materialCategory" type="materialCategoryType" use="optional"/>
			<xs:attribute name="isSystemGenerated" type="systemGenerated" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datafield">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="subfield" maxOccurs="unbounded"/>
				<xs:element ref="indicator" minOccurs="0" maxOccurs="2"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="repeatable" type="xs:boolean" use="required"/>
			<xs:attribute name="mandatory" type="xs:boolean" use="optional"/>
			<xs:attribute name="embaddedFieldsAllowed" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="charposition">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="codelist"/>
			</xs:sequence>
			<xs:attribute name="start" type="xs:int" use="required"/>
			<xs:attribute name="end" type="xs:int" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="defaultValue" type="xs:string" use="optional"/>
			<xs:attribute name="isSystemGenerated" type="systemGenerated" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="subfield">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="charposition" maxOccurs="unbounded"/>
				<xs:element ref="codelist"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="repeatable" type="xs:boolean" use="required"/>
			<xs:attribute name="mandatory" type="xs:boolean" use="optional"/>
			<xs:attribute name="defaultValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="indicator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="internalCodeList"/>
			</xs:sequence>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="index" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="defaultValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="codelist">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="internalCodeList"/>
				<xs:element name="externalCodeListID" type="xs:string"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="internalCodeList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="externalCodeList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute name="source" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="materialCategoryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="a-Map"/>
			<xs:enumeration value="c-Electronic resource"/>
			<xs:enumeration value="d-Globe"/>
			<xs:enumeration value="f-Tactile material"/>
			<xs:enumeration value="g-Projected graphic"/>
			<xs:enumeration value="h-Micro form"/>
			<xs:enumeration value="k-Nonprojected graphics"/>
			<xs:enumeration value="m-Motion picture"/>
			<xs:enumeration value="o-Kit"/>
			<xs:enumeration value="q-Noted music"/>
			<xs:enumeration value="r-Remote-sensing image"/>
			<xs:enumeration value="s-Sound recording"/>
			<xs:enumeration value="t-Text"/>
			<xs:enumeration value="v-Videorecording"/>
			<xs:enumeration value="z-Unspecified"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="materialTypeType">
		<xs:annotation>
			<xs:documentation>BK-Books, CF-Computer files, MP-Maps, MU-Music, CR-Continuing Resources, VM-Visual Materials, MX-Mixed Materials</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="BK"/>
			<xs:enumeration value="CF"/>
			<xs:enumeration value="MP"/>
			<xs:enumeration value="MU"/>
			<xs:enumeration value="CR"/>
			<xs:enumeration value="VM"/>
			<xs:enumeration value="MX"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="systemGenerated">
		<xs:restriction base="xs:string">
			<xs:enumeration value="never"/>
			<xs:enumeration value="may be"/>
			<xs:enumeration value="usually"/>
			<xs:enumeration value="always"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== RAFSoftLab/marcfxeditor/marcfx/src/rs/edu/raf/marcfx/marc21format/xmlfiles/MARC21_format-holdings.xml
<?xml version="1.0" encoding="UTF-8"?>
<format name="MARC 21 format" description="MARC 21 format for holdings data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\nauka\doktorat-softver\doktorat-workspace\marc21.cataloguing.editor\src\marc21\cataloguing\format\xmlfiles\marc21_formatNovo.xsd">
	<leader repeatable="false" name="LEADER" mandatory="true">
		<charposition start="00" end="04" description="Record length" isSystemGenerated="usually"/>
		<charposition start="05" end="05" description="Record status" isSystemGenerated="usually">
			<codelist>
				<internalCodeList>
					<item code="c" value="Corrected or revised"/>
					<item code="d" value="Deleted"/>
					<item code="n" value="New"/>
				</internalCodeList>
			</codelist>
		</charposition>
		<charposition start="06" end="06" description="Type of record" isSystemGenerated="never">
			<codelist>
				<internalCodeList>
					<item code="u" value="Unknown"/>
					<item code="v" value="Multipart item holdings "/>
					<item code="x" value="Single-part item holdings"/>
					<item code="y" value="Serial item holdings"/>
				</internalCodeList>
			</codelist>
		</charposition>
		<charposition start="07" end="07" description="Bibliographic level"/>
		<charposition start="08" end="08" description="Type of control"/>
		<charposition start="09" end="09" description="Character coding scheme" isSystemGenerated="usually"/>
		<charposition start="10" end="10" description="Indicator count" defaultValue="2"/>
		<charposition start="11" end="11" description="Subfield code count" defaultValue="2"/>
		<charposition start="12" end="16" description="Base address of data" isSystemGenerated="usually"/>
		<charposition start="17" end="17" description="Encoding level"/>
		<charposition start="18" end="18" description="Descriptive cataloging form"/>
		<charposition start="19" end="19" description="Multipart resource record level"/>
		<charposition start="20" end="20" description="Length of the length-of-field portion" defaultValue="4"/>
		<charposition start="21" end="21" description="Length of the starting-character-position portion" defaultValue="5"/>
		<charposition start="22" end="22" description="Length of the implementation-defined portion" defaultValue="0"/>
		<charposition start="23" end="23" description="Undefined" defaultValue="0"/>
	</leader>
	<directory repeatable="false">
		<charposition start="00" end="02" description="Tag" isSystemGenerated="always"/>
		<charposition start="03" end="06" description="Field length" isSystemGenerated="always"/>
		<charposition start="07" end="11" description="Starting character position" isSystemGenerated="always"/>
	</directory>
	<controlfield repeatable="false" description="Control Number" name="001" isSystemGenerated="may be"/>
	<controlfield repeatable="false" description="Control Number Identifier" name="003" isSystemGenerated="usually"/>
	<datafield repeatable="true" description="Restrictions on Access Note" name="506">
		<subfield repeatable="false" description="Terms governing access" name="a"></subfield>
		<subfield repeatable="true" description="Jurisdiction" name="b"/>
		<subfield repeatable="true" description="Physical access provisions" name="c" />
		<indicator index="1" description="Restriction">
			<internalCodeList>
				<item code="#" value="No information provided"></item>
				<item code="0" value="No restrictions"></item>
				<item code="1" value="Restrictions apply"></item>
			</internalCodeList>
		</indicator>
	</datafield>
	<datafield repeatable="true" description="Location" name="852">		
		<subfield repeatable="false" description="Location" name="a"/>
		<subfield repeatable="true" description="Sublocation or collection" name="b"/>
		<subfield repeatable="true" description="Shelving location" name="c"/>
		<indicator index="1" description="Shelving scheme">
			<internalCodeList>
				<item code="#" value="No information provided"/>
				<item code="0" value="Library of Congress classification"/>
				<item code="1" value="Dewey Decimal classification"/>
				<item code="2" value="National Library of Medicine classification"/>
				<item code="3" value="Superintendent of Documents classification"/>
				<item code="4" value="Shelving control number"/>
				<item code="5" value="Title"/>
				<item code="6" value="Shelved separately"/>
				<item code="7" value="Source specified in subfield $2"/>
				<item code="8" value="Other scheme"/>
			</internalCodeList>
		</indicator>
	</datafield>	
	<datafield repeatable="true" description="Captions and Pattern - Basic Bibliographic Unit" name="853">
		<subfield repeatable="false" description="First level of enumeration" name="a"></subfield>
		<subfield repeatable="false" description="Second level of enumeration" name="b"></subfield>
		<subfield repeatable="false" description="Third level of enumeration" name="c"></subfield>
		<subfield repeatable="false" description="Fourth level of enumeration" name="d"></subfield>
		<subfield repeatable="false" description="Fifth level of enumeration" name="e"></subfield>
		<indicator index="1" description="Compressibility and expandability">
			<internalCodeList>
				<item code="0" value="Cannot compress or expand"></item>
				<item code="1" value="Can compress but not expand"></item>
				<item code="2" value="Can compress or expand"></item>
				<item code="3" value="Unknown"></item>				
			</internalCodeList>
		</indicator>
	</datafield>
</format>
